[config]
fps = 30 # FPS, default to 30
lyrics = true # defaults to false
genre = false# default to false

[scripts]
# all = "/home/tinker/Programming/Rust/mplayer-client/all.lua"
# list = "/home/tinker/Programming/Rust/mplayer-client/list.lua"
# seeker = "/home/tinker/Programming/Rust/mplayer-client/seeker.lua"
# maps = [
#   "<A-k>" = GoAboveRegion
#   "<A-j>" = GoBelowRegion
#   "k" = GoUp 
#   "j" = GoDown
#   "CR" = PlaySelected
#   "<C-c>" = Close
# ] 
# [keybinds.seeker]
# [keybinds.volume]
# [keybinds.action]
# [keybinds.lyrics]
