[config]
path = "/home/yassine/Music"
sorting = "ByDurationAscending" # ByTitleAscending, ByTitleDescending, ByDurationAscending, ByDurationDescending, Shuffle 
repeat = "AllMusics" # Dont, ThisMusic
