name: "Build mplayer-client via Nix"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Building package
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix --extra-experimental-features "nix-command flake" build --impure
